
// Metamask
export const METAMASK_ACCOUNT = 'METAMASK_ACCOUNT';
export const METAMASK_NETWORK = 'METAMASK_NETWORK';

// Global Elections
export const ADD_ELECTIONS = 'ADD_ELECTIONS'

export const ADD_USER_ELECTIONS = 'ADD_USER_ELECTIONS'
export const INSERT_USER_ELECTION = 'INSERT_USER_ELECTION'

export const ADD_ADMIN_ELECTIONS = 'ADD_ADMIN_ELECTIONS'

export const ADD_CANDIDATE_ELECTIONS = 'ADD_CANDIDATE_ELECTIONS'

export const UPDATE_CURRENT_ELECTION = 'UPDATE_CURRENT_ELECTION'
export const ELECTION_VOTING_ADDRESS = 'ELECTION_VOTING_ADDRESS'
export const ELECTION_REGISTRATION_ADDRESS = 'ELECTION_REGISTRATION_ADDRESS'
export const ELECTION_ADMIN_ADDRESS = 'ELECTION_ADMIN_ADDRESS'
export const ELECTION_NAME = 'ELECTION_NAME'
export const ELECTION_R_BEGIN = 'ELECTION_R_BEGIN'
export const ELECTION_R_END = 'ELECTION_R_END'
export const ELECTION_V_BEGIN = 'ELECTION_V_BEGIN'
export const ELECTION_V_END = 'ELECTION_V_END'

export const STATUS_VOTER_APPLIED = 'STATUS_VOTER_APPLIED'
export const STATUS_VOTER_CHECKED = 'STATUS_VOTER_CHECKED'
export const STATUS_VOTER_VALID = 'STATUS_VOTER_VALID'
export const STATUS_VOTER_VOTED = 'STATUS_VOTER_VOTED'
export const STATUS_VOTER_TIME_APPLIED = 'STATUS_VOTER_TIME_APPLIED'
export const STATUS_VOTER_TIME_CHECKED = 'STATUS_VOTER_TIME_CHECKED'
export const STATUS_VOTER_NOMINATED = 'STATUS_VOTER_NOMINATED'
export const STATUS_VOTER_ID_CODE = 'STATUS_VOTER_ID_CODE'

export const STATUS_CANDIDATE_APPLIED = 'STATUS_CANDIDATE_APPLIED'
export const STATUS_CANDIDATE_VALID = 'STATUS_CANDIDATE_VALID'
export const STATUS_CANDIDATE_TIME_APPLIED = 'STATUS_CANDIDATE_TIME_APPLIED'
export const STATUS_CANDIDATE_TIME_NOMINATED = 'STATUS_CANDIDATE_TIME_NOMINATED'

export const ELECTION_PUBLIC_KEY = 'ELECTION_PUBLIC_KEY'
export const ELECTION_PRIVATE_KEY = 'ELECTION_PRIVATE_KEY'

export const ELECTION_CANDIDATES = 'ELECTION_CANDIDATES'

export const ELECTION_VOTES = 'ELECTION_VOTES'

export const ELECTION_STAGE = 'ELECTION_STAGE'

export const ELECTION_TYPE = 'ELECTION_TYPE'